# Using 'Rest Client library'

@hostname = http://localhost:5000/articles

get {{hostname}}

###
get {{hostname}}/React

###
post {{hostname}} 
content-type: application/json

{
    "title": "IGI",
    "content": "Creator of this Cheatsheet saying Hi to youu"
}

###
PUT  {{hostname}}/EJS_4 HTTP/1.1
content-type: application/json

{
    "title": "IGI"
}