# Using 'Rest Client library'

@hostname = http://localhost:5000/articles

get {{hostname}}
###
get {{hostname}}/React


###
POST {{hostname}} HTTP/1.1
content-type: application/x-www-form-urlencoded

&content=Creator of this Cheatsheet saying Hi to youu123
&title=IGI_123

# {
#     "content": "Creator of this Cheatsheet saying Hi to youu",
#     "title": "IGI"
# }


###
put {{hostname}}/EJS_4 HTTP/1.1
content-type: application/x-www-form-urlencoded

{
    "title": "IGI"
}